id: P40840BE8
initial_creation_type: input
source_metadata:
  title: Atiśa Dīpaṃkara Series
  language: fr
  description: Atiśa Dīpaṃkara Śrījñāna (982–1054), known as Jowo Jé Palden Atisha
    (jo bo rje dpal ldan a ti sha) in Tibetan, was a great Indian master and scholar.
    He spent the last ten years of his life in Tibet, teaching and translating texts,
    and was instrumental in reinvigorating Buddhism there after a period of persecution
    and decline.
  volume:
    5bbb2b74db80400c87a0e8189faae695:
      title: Heart Treasure for the Warriors Who Long for Liberation
      parent: Advice
    753408deb3a54f1695f374a4116283d6:
      title: The Lamp for the Path to Enlightenment
      parent: Advice
    ce5147a2fe2a4c2ca82f77ff71e434cc:
      title: 'Bestower of Supreme Blessings: Guru Yoga of the Great Incomparable Lord
        Atiśa'
      parent: Guru Yoga
    8b99f4dddd0e4eadba23a5d399acd105:
      title: The Bodhisattva’s Garland of Jewels
      parent: Mind Training
    9fee3cf283c04e1b92e37d65afeb39e4:
      title: An Extremely Concise Praise of the Twenty-One Tārās
      parent: Praise
    ae5349b0fa8a45829410096f30d7d774:
      title: Light Offering Prayer
      parent: Prayers
    d1922999b08044368c237d4f9215b171:
      title: Prayer for the Future of the Dharma
      parent: Prayers
    d6317292c4f84ed288db8a996349d4ab:
      title: Prayer to Ārya Tārā
      parent: Prayers
    c276187a75d94bd5b7ad8c60c765d528:
      title: Short Prayer to Atiśa
      parent: Prayers
created_at: '2022-03-01T02:10:55.972312'
last_modified_at: '2022-03-01T02:10:55.972314'
